version: '3.3'

services:
 express:
  build: .
  volumes:
  - ./:/UserManager
  ports:
  - '3000:3000'
  tty: true
  links:
  - mongo

 mongo:
  image: mongo
  ports:
  - '27017:27017'
  restart: always
